#!/bin/sh

source /etc/envvars

# hit local healthcheck to force create new log
curl -s 'http://127.0.0.1/healthcheck?cron=daily-backup'

# reload nginx to make sure new log is created
/usr/local/openresty/bin/openresty -s reload

# if aws env are entered, then we can do backup
if [[ "$AWS_PATH" != '' ]]; then
  LOGDIR="/usr/local/openresty/nginx/logs/*.plog";
  COUNTER=0;

  # sync all plog files
  for line in `ls -t $LOGDIR`
  do
    #echo $line;
    file=`echo $line | awk -F "/" '{ print $NF }'`;
    #echo $file;
    YEAR=`echo $file | cut -d "-" -f 1`;
    MONTH=`echo $file | cut -d "-" -f 2`;
    DAY=`echo $file | cut -d "-" -f 3`;
    HOUR=`echo $file | cut -d "-" -f 4`;

    # only process with valid month
    if [ ! -z "$MONTH"  ]; then
      # skip first file since it's still collecting data
      COUNTER=$(expr $COUNTER + 1)
      if [ $COUNTER -gt 1 ]; then
        s3file=`aws s3 ls s3://$AWS_PATH/year=$YEAR/month=$MONTH/day=$DAY/$file`
        RETVAL=$?
        if [ $RETVAL -ne 0 ]
        then
          aws s3 cp $line s3://$AWS_PATH/year=$YEAR/month=$MONTH/day=$DAY/$file
          rm -f $line
        fi
      fi
    fi
  done
fi
