#!/bin/sh

# update geoip database
cd /tmp
curl -fSL https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz -o /tmp/GeoLiteCity.dat.gz
gunzip -f GeoLiteCity.dat.gz
rm -f /usr/local/openresty/nginx/conf/conf.d/GeoLiteCity.dat
mv GeoLiteCity.dat /usr/local/openresty/nginx/conf/conf.d/GeoLiteCity.dat

# reload nginx to prevent file lock and immediately clear cache
/usr/local/openresty/bin/openresty -s reload
